USE project;

CREATE TABLE `AUTHORITY` (
  `AUTHORITY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDBY` varchar(30) NOT NULL,
  `CREATEDDATETIME` datetime NOT NULL,
  `UPDATEDBY` varchar(30) DEFAULT NULL,
  `UPDATEDDATETIME` datetime DEFAULT NULL,
  `AUTHORITY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AUTHORITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


insert into `AUTHORITY`(`AUTHORITY_ID`,`CREATEDBY`,`CREATEDDATETIME`,`UPDATEDBY`,`UPDATEDDATETIME`,`AUTHORITY`) values (1,'admin','2011-07-08 00:00:00','admin','2011-07-08 00:00:00','ROLE_ALLACCESS');
insert into `AUTHORITY`(`AUTHORITY_ID`,`CREATEDBY`,`CREATEDDATETIME`,`UPDATEDBY`,`UPDATEDDATETIME`,`AUTHORITY`) values (2,'admin','2011-07-08 00:00:00','admin','2011-07-08 00:00:00','IS_AUTHENTICATED_ANONYMOUSLY');
