USE project;

CREATE TABLE `USER_AUTHORITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDBY` varchar(30) NOT NULL,
  `CREATEDDATETIME` datetime NOT NULL,
  `UPDATEDBY` varchar(30) DEFAULT NULL,
  `UPDATEDDATETIME` datetime DEFAULT NULL,
  `AUTHORITY_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKBC8EF3AF78800769` (`USER_ID`),
  KEY `FKBC8EF3AF44997AAB` (`AUTHORITY_ID`),
  CONSTRAINT `FKBC8EF3AF44997AAB` FOREIGN KEY (`AUTHORITY_ID`) REFERENCES `authority` (`AUTHORITY_ID`),
  CONSTRAINT `FKBC8EF3AF78800769` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


insert into `USER_AUTHORITY`(`ID`,`CREATEDBY`,`CREATEDDATETIME`,`UPDATEDBY`,`UPDATEDDATETIME`,`AUTHORITY_ID`,`USER_ID`) values (1,'admin','2011-07-08 00:00:00','admin','2011-07-08 00:00:00',1,1);
insert into `USER_AUTHORITY`(`ID`,`CREATEDBY`,`CREATEDDATETIME`,`UPDATEDBY`,`UPDATEDDATETIME`,`AUTHORITY_ID`,`USER_ID`) values (2,'admin','2011-07-08 00:00:00','admin','2011-07-08 00:00:00',1,2);
